# Generated by Django 5.0.3 on 2024-04-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('apellido', models.CharField(blank=True, max_length=32, null=True)),
                ('fecha', models.CharField(blank=True, max_length=32, null=True)),
                ('tipoPersona', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
