# Generated by Django 5.0.3 on 2024-04-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='codigoPersona',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
