# Generated by Django 5.0.3 on 2024-04-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_personas_codigopersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True)),
                ('residencia', models.CharField(blank=True, max_length=32, null=True)),
                ('personaRel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.personas')),
            ],
        ),
    ]
