# Generated by Django 5.0.3 on 2024-04-03 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_datosadicionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareasxPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=32, null=True)),
                ('personaRel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3.personas')),
            ],
        ),
    ]
